sudo: false
language: cpp
compiler: g++
os:
  - linux
#  - osx

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake -j2 --build .
  - ctest -j2 -C Release -T test --output-on-failure
